package kr.co.bizframe.camel.cxf.hello.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T19:10:32.812+09:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://server.hello.cxf.camel.bizframe.co.kr/", name = "HelloPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloPortType {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.hello.cxf.camel.bizframe.co.kr/", className = "kr.co.bizframe.camel.cxf.hello.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.hello.cxf.camel.bizframe.co.kr/", className = "kr.co.bizframe.camel.cxf.hello.client.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "http://server.hello.cxf.camel.bizframe.co.kr/")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "http://server.hello.cxf.camel.bizframe.co.kr/")
        java.lang.String arg0
    );
}
