package kr.co.bizframe.camel.cxf.hello.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T19:10:32.850+09:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "Hello",
                  wsdlLocation = "file:helloService.xml",
                  targetNamespace = "http://server.hello.cxf.camel.bizframe.co.kr/")
public class Hello extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.hello.cxf.camel.bizframe.co.kr/", "Hello");
    public final static QName HelloPort = new QName("http://server.hello.cxf.camel.bizframe.co.kr/", "HelloPort");
    static {
        URL url = null;
        try {
            url = new URL("file:helloService.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Hello.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:helloService.xml");
        }
        WSDL_LOCATION = url;
    }

    public Hello(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Hello(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Hello() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Hello(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Hello(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Hello(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloPortType
     */
    @WebEndpoint(name = "HelloPort")
    public HelloPortType getHelloPort() {
        return super.getPort(HelloPort, HelloPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloPortType
     */
    @WebEndpoint(name = "HelloPort")
    public HelloPortType getHelloPort(WebServiceFeature... features) {
        return super.getPort(HelloPort, HelloPortType.class, features);
    }

}
